### ISSUE TITLE
Test out elasticsearch right next to dataproc cluster

### ISSUE THREAD

**Issue by djnesmith** [icxmedia/dataproc-scripts#15]
FEATURE
---
#### Description
- Jon is putting a version of dr-evil in the same network as our dataproc cluster.  We need to test out if we can load data from there as well as right data back to it.

**Comment by alexmitc** [comment]
Is this the same as https://app.zenhub.com/workspaces/all-repos-55f804b9338ed0e614f591f1/issues/icxmedia/product/1508 @djnesmith  - if so let's close as duplicate.

**Comment by djnesmith** [comment]
@alexmitc yep, i closed that other one
